### ISSUE TITLE
Stream forcefully closed error

### ISSUE THREAD

**Issue by bbernhard** [Pr0Ger/PyAPNs2#29]
Hello, 

first of all many thanks for the great package!
I just tried the code snippet that's shown in the `README`, but whenever I execute it, I get the following error:

```
    client.send_notification(token, payload)
  File "/usr/local/lib/python3.4/dist-packages/apns2/client.py", line 38, in send_notification
    stream_id = self.__connection.request('POST', url, json_payload, headers)
  File "/usr/local/lib/python3.4/dist-packages/hyper/http20/connection.py", line 281, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "/usr/local/lib/python3.4/dist-packages/hyper/http20/connection.py", line 546, in endheaders
    stream = self._get_stream(stream_id)
  File "/usr/local/lib/python3.4/dist-packages/hyper/http20/connection.py", line 289, in _get_stream
    raise StreamResetError("Stream forcefully closed")
hyper.http20.exceptions.StreamResetError: Stream forcefully closed


```

Does anyone have an idea what I am doing wrong here? 

Many thanks!

Have a nice day,
Bernhard

**Comment by yichengchen** [comment]
maybe your push cert is wrong

**Comment by bbernhard** [comment]
@yichengchen Many thanks for your reply! You were completely right, that was the issue. 

Does it make sense to add a line or two to the README file that describes how to create a working *.pem file? I know, that's usually something that the Apple documentation should cover, but it looks like that I am not the only one that is/was struggling with that: 

http://stackoverflow.com/questions/41211416/im-not-able-to-find-any-information-on-this-error-im-seeing-streamreseterror
https://github.com/Pr0Ger/PyAPNs2/issues/7

Another thing I noticed is, that I needed to change the following line 
`client.send_notification(token_hex, payload)`
and add my bundle identifier `topic` parameter:
`client.send_notification(token_hex, payload, topic=`com.example.example`)
Without the `token` parameter I was always getting a `TopicMissing` exception.

Did I do something wrong here or is that missing in the documentation?

Have a nice day,
Bernhard

**Comment by Pr0Ger** [comment]
About creating certificates: I'm not sure it should be in the README file because there are a lot of different cases when push certificate is created: it can be usual pushes, VoIP pushes, web site pushes, pushes for WatchKit complications; covering all of these will be probably a huge paragraph. And there are different ways of generating it, as I already told in mentioned issue I use `pem` tool for creating certificates, but I don't want to impose it by mentioning in README.

About passing topic: Apple documentation states that we can omit `apns-topic` header in some cases, that's why I made it optional. But almost always it's a required field, so current version (available in master branch) have this field as required.

**Comment by zhanghonged** [comment]
I also encountered the same problem, how can I solve it?
